name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write # Needed for signing the gem

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install

    - name: Run tests
      run: |
        bundle exec rake test

    - name: Build gem
      run: |
        bundle exec rake build

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          pkg/*.gem
        generate_release_notes: true
        draft: false
        prerelease: false

    - name: Publish to RubyGems
      run: |
        bundle exec rake release
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }} 